// Builds the single-file artifact web/civics-test-study-tool.html from web/src
// (template, styles, JS modules) and web/data (generated question bank).
// The artifact is checked into git, deployable via `cp` to dist/, and openable
// from file:// — everything is inlined, no runtime fetches or module loads.
//
// Run: npm run build   (in web/)
// Data refresh + build: npm run sync
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const here = p => fileURLToPath(new URL(p, import.meta.url));

if (!existsSync(here('./data/bank.generated.js'))) {
  console.error('error: web/data/bank.generated.js is missing — generate it first:');
  console.error('  node ../android/tools/extract-questions.mjs   (or: npm run sync)');
  process.exit(1);
}

const result = await build({
  entryPoints: [here('./src/main.js')],
  bundle: true,
  write: false,
  minify: true,
  format: 'iife',
  outfile: 'bundle.js',
  logLevel: 'warning',
});
const js = result.outputFiles
  .find(f => f.path.endsWith('.js')).text
  .replace(/<\/script/gi, '<\\/script'); // never terminate the inline script tag early
const css = result.outputFiles.find(f => f.path.endsWith('.css')).text;

let html = readFileSync(here('./src/index.html'), 'utf8');
for (const [token, file] of [['__FAVICON_DATA_URI__', './icons/favicon-32.png'], ['__TOUCH_ICON_DATA_URI__', './icons/apple-touch-icon.png']]) {
  if (!html.includes(token)) throw new Error(`placeholder ${token} not found in src/index.html`);
  if (!existsSync(here(file))) throw new Error(`${file} missing — regenerate it: python3 ../assets/generate_icons.py`);
  html = html.split(token).join('data:image/png;base64,' + readFileSync(here(file)).toString('base64'));
}
for (const [token, content] of [['/*__BUILD_CSS__*/', css], ['/*__BUILD_JS__*/', js]]) {
  if (!html.includes(token)) throw new Error(`placeholder ${token} not found in src/index.html`);
  html = html.split(token).join(content);
}
html = html.replace('<!DOCTYPE html>', () =>
  '<!DOCTYPE html>\n' +
  '<!-- GENERATED by web/build.mjs from web/src/ + web/data/ — do not edit by hand.\n' +
  '     Edit the sources, then run: npm run build (in web/). Data refresh: npm run sync. -->');
writeFileSync(here('./civics-test-study-tool.html'), html);
console.log(
  `wrote web/civics-test-study-tool.html (${(html.length / 1024).toFixed(0)} KB total, ` +
  `${(js.length / 1024).toFixed(0)} KB js, ${(css.length / 1024).toFixed(0)} KB css)`,
);
