// Builds desktop/dist/ for the Tauri shell from the SHARED web sources
// (../web/src + ../web/data). Engine, settings, i18n, and all UI modules are
// bundled byte-identical to the web app; the one substitution is
// web/src/speech.js -> desktop/src/native-speech.js, which routes utterances
// to the OS speech engine (Windows SAPI / Linux speech-dispatcher) through
// Tauri commands instead of the Web Speech API.
//
// Unlike the web build, the Google Fonts <link>s are stripped: the desktop
// app makes no network requests at all (system font fallbacks: Inter ->
// system-ui, Fraunces -> Georgia), keeping the no-data-collection promise.
//
// Run: npm run build   (in desktop/)
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { build } from 'esbuild';

const here = p => fileURLToPath(new URL(p, import.meta.url));
const WEB_SPEECH = here('../web/src/speech.js').toLowerCase();
const NATIVE_SPEECH = here('./src/native-speech.js');

/* Redirect every import of web/src/speech.js (engine.js, main.js, ui/*) to the
   native driver. Matched by resolved absolute path so ui/settings.js etc. also
   hit it, while unrelated speech.js files would pass through untouched. */
const swapSpeechDriver = {
  name: 'swap-speech-driver',
  setup(b) {
    b.onResolve({ filter: /(^|[\\/])speech\.js$/ }, args => {
      if (resolve(args.resolveDir, args.path).toLowerCase() === WEB_SPEECH) {
        return { path: NATIVE_SPEECH };
      }
    });
  },
};

const result = await build({
  entryPoints: [here('../web/src/main.js')],
  bundle: true,
  write: false,
  minify: true,
  format: 'iife',
  outfile: 'bundle.js',
  logLevel: 'warning',
  plugins: [swapSpeechDriver],
});
const js = result.outputFiles
  .find(f => f.path.endsWith('.js')).text
  .replace(/<\/script/gi, '<\\/script'); // never terminate the inline script tag early
const css = result.outputFiles.find(f => f.path.endsWith('.css')).text;

// Same data-URI icon inlining as web/build.mjs, from the shared web icons.
let html = readFileSync(here('../web/src/index.html'), 'utf8');
for (const [token, file] of [['__FAVICON_DATA_URI__', '../web/icons/favicon-32.png'], ['__TOUCH_ICON_DATA_URI__', '../web/icons/apple-touch-icon.png']]) {
  const iconPath = here(file);
  if (!existsSync(iconPath)) throw new Error(`${file} missing — regenerate it: python3 ../assets/generate_icons.py`);
  html = html.split(token).join('data:image/png;base64,' + readFileSync(iconPath).toString('base64'));
}
// Desktop: no network — drop the Google Fonts preconnects and stylesheet link.
html = html
  .replace(/<link rel="preconnect" href="https:\/\/fonts\.[^"]*"[^>]*>\r?\n?/g, '')
  .replace(/<link href="https:\/\/fonts\.googleapis\.com[^"]*" rel="stylesheet">\r?\n?/g, '');
if (html.includes('fonts.googleapis.com')) throw new Error('desktop build must not reference Google Fonts');
for (const [token, content] of [['/*__BUILD_CSS__*/', css], ['/*__BUILD_JS__*/', js]]) {
  if (!html.includes(token)) throw new Error(`placeholder ${token} not found in web/src/index.html`);
  html = html.split(token).join(content);
}
html = html.replace('<!DOCTYPE html>', () =>
  '<!DOCTYPE html>\n' +
  '<!-- GENERATED by desktop/build.mjs from web/src/ + web/data/ — do not edit by hand.\n' +
  '     Edit the sources (web/src, or desktop/src/native-speech.js), then run: npm run build. -->');

rmSync(here('./dist'), { recursive: true, force: true });
mkdirSync(here('./dist'));
writeFileSync(here('./dist/index.html'), html);
console.log(
  `wrote desktop/dist/index.html (${(html.length / 1024).toFixed(0)} KB total, ` +
  `${(js.length / 1024).toFixed(0)} KB js, ${(css.length / 1024).toFixed(0)} KB css)`,
);
